### ISSUE TITLE
Newquay squawk allocation changes (2211)

### ISSUE THREAD

**Issue by hazzas-99** [VATSIM-UK/uk-controller-api#1101]
Effective 3 November 2022

Newquay ranges amended:

- 1730-1746
- 1750-1756

LARS squawk is now 1757, which I assume isn't in the API?

**Comment by danielbutton** [comment]
Worth noting that 1747 is the Basic Service Conspicuity Code? :)

**Comment by danielbutton** [comment]
Squawk range allocation as per current procedures:
Arrivals 1730-1737 (assigned to Radar 1)
Departures 1740-1746 (assigned to TWR)
LARS - 1750-1756 (assigned to Radar 2 when split)

Newquay Basic Service Conspicuity - 1747
Newquay LARS when no other codes available - 1757 (usually assigned to locally-based aircraft)

Not sure if we can assign codes to specific controllers or functions but thought I'd add this for expansion on Harry's changes :)

**Comment by AndyTWF** [comment]
Hi both - I've just deployed the squawk range part of the admin panel, and have made these changes :)
