### ISSUE TITLE
Expand Roles

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/uk-controller-api#1183]
Expand the roles system to allow more fine-grained permissions. For example, allow edit access to stands only.

This will allow ops to grant access for contributors to update the stand data, for example.

**Comment by KHardern** [comment]
Thanks for this. Obviously you might prefer to make it flexible, but from purely the perspective of what could "approved non-ops people do", I would suggest only:
- Stands
- Navaids and Holds
