### ISSUE TITLE
Northolt RNAV SIDs Initial Climb

### ISSUE THREAD

**Issue by danielbutton** [VATSIM-UK/uk-controller-api#1216]
Ref: https://github.com/VATSIM-UK/UK-Sector-File/pull/4621

To be added for AIRAC 2302 - Northolt (EGWU) RNAV SIDs:
BUZAD4X & BUZAD2Y
CPT6X & CPT5Y
MATCH2X & MATCH2Y
RTC07 & RTC25

Initial climbs for the above are all 3000ft

CHARLIE and ROMEO initial climbs are now 2000ft

Thanks! :)

**Comment by AndyTWF** [comment]
Thanke @hazzas-99!
