### ISSUE TITLE
Delete EGQB and EGXV closed airfields

### ISSUE THREAD

**Issue by hazzas-99** [VATSIM-UK/uk-controller-api#1312]
As per https://github.com/VATSIM-UK/UK-Sector-File/pull/4577, these airfields are now closed and removed from our other sources of data - however, I get a 500 internal error when trying to delete them from the API admin panel

**Comment by AndyTWF** [comment]
Hi @hazzas-99 sorry for the delay, this is now done :) I've fixed the bug and deleted EGXV for you.

This should work properly in the future - the only thing to bear in mind is that we can't delete any airfields tied to TMAs... but I doubt Heathrow, Glasgow and Manchester are going anywhere any time soon :D
