### ISSUE TITLE
Gatwick prenote/release updates

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-api#192]
New prenote/release procedures as of 2020/08

![image](https://user-images.githubusercontent.com/12017284/87917907-93509800-ca6d-11ea-8f39-88b67a13e774.png)

Before issuing a release as FIN for traffic to EGLL/EGWU/EGLC/EGMC/EGKB, a release is required from the receiving controller (TC SE) - is it possible to code this in too?

**Comment by AndyTWF** [comment]
Hi @hsugden have updated the prenotes, have made separate issue for turning departure releases into a feature
