### ISSUE TITLE
Squawk Assignment Primary Key

### ISSUE THREAD

**Issue by VATSIMUK** [VATSIM-UK/uk-controller-api#205]
## Error in UK Controller Plugin API

**Illuminate\Database\QueryException** in **PUT /squawk-assignment/IBK3503**
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0431-EGPH' for key 'unit_discrete_squawk_assignments.unit_discrete_squawk_assignments_code_unit_unique' (SQL: insert into `unit_discrete_squawk_assignments` (`callsign`, `unit`, `code`, `created_at`) values (IBK3503, EGPH, 0431, 2020-07-23 15:11:41))

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/uk-controller-plugin-api-1/errors/5f19a8ad9b84a40017203b95?event_id=5f19a8ad005b761572ea0000&i=gh&m=ci)

## Stacktrace

    app/Allocator/Squawk/Local/UnitDiscreteSquawkAllocator.php:95 - App\Allocator\Squawk\Local\UnitDiscreteSquawkAllocator::App\Allocator\Squawk\Local\{closure}
    app/Allocator/Squawk/Local/UnitDiscreteSquawkAllocator.php:99 - App\Allocator\Squawk\Local\UnitDiscreteSquawkAllocator::App\Allocator\Squawk\Local\{closure}
    app/Allocator/Squawk/Local/UnitDiscreteSquawkAllocator.php:101 - App\Allocator\Squawk\Local\UnitDiscreteSquawkAllocator::allocate
    app/Services/SquawkService.php:117 - App\Services\SquawkService::App\Services\{closure}
    app/Services/SquawkService.php:122 - App\Services\SquawkService::assignSquawk
    app/Services/SquawkService.php:85 - App\Services\SquawkService::assignLocalSquawk
    app/Http/Controllers/SquawkController.php:178 - App\Http\Controllers\SquawkController::assignLocalSquawk
    app/Http/Controllers/SquawkController.php:99 - App\Http\Controllers\SquawkController::assignSquawk
    app/Http/Middleware/UserIsDisabled.php:42 - App\Http\Middleware\UserIsDisabled::handle
    app/Http/Middleware/UserIsBanned.php:43 - App\Http\Middleware\UserIsBanned::handle
    app/Http/Middleware/Authenticate.php:73 - App\Http\Middleware\Authenticate::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/uk-controller-plugin-api-1/errors/5f19a8ad9b84a40017203b95?event_id=5f19a8ad005b761572ea0000&i=gh&m=ci)

*Created by Calum Towers via Bugsnag*

**Comment by vatsim-uk-pa** [comment]
This issue has been linked to an error in Bugsnag
[**Illuminate\Database\QueryException** in **PUT /squawk-assignment/CGOLD**](https://app.bugsnag.com/vatsim-uk/uk-controller-plugin-api-1/errors/5f19e5fb554ea80018842f7a?event_id=5f1b18fc005b72a568860000&i=gh&m=li)

**Comment by VATSIMUK** [comment]
An error linked to this issue has been reopened in Bugsnag
[**PDOException** in **PUT /squawk-assignment/EZY87WK**](https://app.bugsnag.com/vatsim-uk/uk-controller-plugin-api-1/errors/5f19e5fb554ea80018842f7a?event_id=5fe33e1000659836277e0000&i=gh&m=ra)
