### ISSUE TITLE
EGLL GND "top-down"

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-api#22]
Is it an issue that the ground position to log on first varies dependent on the runway configuration? I notice that only EGLL_2_GND has "top-down" responsibilities for EGLL, but EGLL_1_GND logs on first on easterlies

[https://community.vatsim.uk/topic/34150-2017-03-02-londonheathrow-egll-gmc-opening-order-and-aor-changes/?tab=comments#comment-309806](https://community.vatsim.uk/topic/34150-2017-03-02-londonheathrow-egll-gmc-opening-order-and-aor-changes/?tab=comments#comment-309806)

**Comment by AndyTWF** [comment]
Good spot - I've updated the dependencies to include EGLL_1_GND too after 2. Obviously this would mean that 2 will always take precedence over 1, but as the log-on order requires DEL to open before multiple GNDs, that's not a problem 👍
