### ISSUE TITLE
Scottish MSL calculations

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-api#315]
In line with the upcoming Scottish vMATS, 1013 hPa will be treated as:

- Low pressure in the Scottish TMA
- Low pressure in the Belfast TMA
- High pressure at EGPD
- High pressure at EGPB
- Low pressure for any other airfield MSLs, if calculated

My apologies if this is actually a plugin thing - if someone can point me to where this kind of thing is stored, I am happy to try and update it myself!

**Comment by AndyTWF** [comment]
Hi Harry, this is the right place! I've made the changes and will release them alongside the other changes for 2020/13 :)
