### ISSUE TITLE
Covid related stand use changes @ EGLL

### ISSUE THREAD

**Issue by luke11brown** [VATSIM-UK/uk-controller-api#356]
Use stands based on COVID schedules.

i.e. T4 closed, BA all @ T5
Again, happy to submit PR if you point me in the right direction!

**Comment by AndyTWF** [comment]
Hi Luke - happy to do this, but would want to get an opinion from someone in ops first. We've tried to enforce the latest allocation guide, so would be confusing if we differ from it!
