### ISSUE TITLE
Implementation of Daventry standalone position

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-api#403]
With reference to: https://github.com/VATSIM-UK/UK-Sector-File/issues/3417

**LON_M_CTR** - **120.020** (120.025) - EuroScope controller identifier **LM**

Effective from **25 February 2021** (AIRAC 2102)

# Sector Ownership Order

## AC Daventry

**LON_M (LM)** - LON_C (LC) - LON_SC (LSC) - LON (L)

## TC North West

LTC_NW (TCNW) - LTC_N (TCN) - LTC (TC) - **LON_M (LM)** - LON_C (LC) - LON_SC (LSC) - LON (L)

# Airfield Top-Down

## EGNX / EGTC

LTC_CW (WELIN) - LTC_M (TCM) - LON_CL (LCL) - LON_CE (LCE) - **LON_M (LM)** - LON_C (LC) - LON_SC (LSC) - LON (L)

## EGBB / EGTK

LTC_CO (COWLY) - LTC_M (TCM) - LON_CW (LCW) - **LON_M (LM)** - LON_C (LC) - LON_SC (LSC) - LON (L)

## EGSS / EGGW / EGSC

LTC_NW (TCNW) - LTC_N (TCN) - LTC (TC) - LTC_M (TCM) - LON_CL (LCL) - LON_CE (LCE) - **LON_M (LM)** - LON_C (LC) - LON_SC (LSC) - LON (L)

# Changes to Handoff Procedures

All departures that were previously transferred to either AC Daventry or TC North West by ADC/APC controllers now have one additional position in the handoff order. This revised order is the same as detailed in the section above.

## Thames BPK/CPT Departures

Additionally, although the handoff order for BPK/CPT is determined by the presence of TC NE coverage, we will be adding LM at the _very end_ of the handoff order for both Runway 09 & 27 departures.

Thus, the handoff order becomes:

- Runway 27 BPK/CPT - Thames, Thames' top-down, TC NE, TC NE's top-down, **LM**
- Runway 09 BPK/CPT - TC NE, TC NE's top-down, **LM**, Thames, Thames' top-down

**Comment by AndyTWF** [comment]
Hi @hsugden - LON M is already in the API, but we’ll need to do a tad more to add them onto the end of the Thames orders :)

**Comment by hsugden** [comment]
Oops! You're just too on it 😄 I wondered where the api-change-needed trigger had sent the issue...

**Comment by AndyTWF** [comment]
Haha yes it came through just as there was nothing being removed in this change I hopped on it ahead of time! I’ll take a look at adding them to Thames this week :)

**Comment by cbyworth** [comment]
@AndyTWF 
Sorry change of plan for Thames.
LM is now after Thames for both 09 & 27, so...

27 B&C - Thames, Thames' top-down, TC NE, TC NE's top-down, LM
09 B&C - TC NE, TC NE's top-down, Thames, Thames' top-down, LM

**Comment by AndyTWF** [comment]
No problem - you caught me just in time! I've done this
