### ISSUE TITLE
Add SID for the new KK -> LL/WU clearance

### ISSUE THREAD

**Issue by VATSIMUK** [VATSIM-UK/uk-controller-api#416]
https://github.com/VATSIM-UK/UK-Sector-File/issues/3464

**Comment by hsugden** [comment]
26L/R initial climb - 4000ft. If it's also possible to add H075 to the 'strip/tag', that would be great 

08L/R initial climb - 6000ft. Again, H090 also assigned to the aircraft would be a bonus

**Comment by AndyTWF** [comment]
Thanks @hsugden - initial heading isn't something we can do, but an upcoming refactor to UKCPs data will make it possible!

**Comment by AndyTWF** [comment]
Ah, one other thing @hsugden - could they be named differently for each runway? Rn UKCP doesn't tie sids to runways, so something like BIGHDG08 / BIGHDG26 would allow us to do this

**Comment by hsugden** [comment]
> Ah, one other thing @hsugden - could they be named differently for each runway? Rn UKCP doesn't tie sids to runways, so something like BIGHDG08 / BIGHDG26 would allow us to do this

Will pass this on to my sector friends!

**Comment by hsugden** [comment]
Change to names coming in https://github.com/VATSIM-UK/UK-Sector-File/pull/3499
