### ISSUE TITLE
Multiple RPS/MSL Sources

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/uk-controller-api#461]
- At the moment, we draw RPS/MSL from different sources to the VATSIM METAR server.
- This can lead to inconsistencies when the server is behind RW, or has issues.
- Unify under the VATSIM metar server.

**Comment by hsugden** [comment]
![image](https://user-images.githubusercontent.com/12017284/113772925-3d1ba600-971d-11eb-8cc3-489896a3961c.png)

Not entirely sure the London calculation is right...? Time 2015Z today, all METARs are 1950Z.

**Comment by AndyTWF** [comment]
@hsugden the calculation is correct, but what you’re probably seeing is an issue we are having right now where updates seem to stop being broadcast to you after a while.
