### ISSUE TITLE
Add Gravity VA Preferred Stands

### ISSUE THREAD

**Issue by cbyworth** [VATSIM-UK/uk-controller-api#730]
Gravity VA have requested if we could add their preferred stands for Heathrow into UKCP. The list they've provided seems "realistic" (in the sense that Cargo is at T6, they've not used anything at T5) so I am happy to accept from an Ops perspective.

These are their requests:
![image](https://user-images.githubusercontent.com/45854780/144716350-d4937bbc-507c-4e33-ab0a-1d525f7c0d9b.png)

Note, they've used Wake Category indicators but they actually categorise by wing-span (which doesn't align to ICAO A-F categories).  Their fleet is listed here: https://www.flygravity.aero/#fleet

Would this be possible to add?

Thanks! And let me know if you need any more info.

Chad

**Comment by AndyTWF** [comment]
Hiya - do they use a different callsign / flightplan remarks for their cargo flights? UKCP only distinguishes Cargo flights by their airline at the moment.

If we add all these gates for Gravity, UKCP will just pick one at random that's closest to their WTC - if that's acceptable?

**Comment by cbyworth** [comment]
Hi.
![Uploading Screenshot_20211205-173746.png…]()

**Comment by cbyworth** [comment]
Hi,
![Screenshot_20211205-173746](https://user-images.githubusercontent.com/45854780/144759877-f7331b97-6228-4822-a8e9-14b1b8ba9e72.png)

Would it (easily) workable with the RMK?

**Comment by AndyTWF** [comment]
Yep I can work with that!
