### ISSUE TITLE
EGPD stand allocation

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-api#752]
LOG92DS into EGPD around about 2150 on 20/12/2021 - from EKEB (intl.) - so should've been allocated one of stands 1-4. Was instead allocated stand 11.

Latest allocation guide:

![image](https://user-images.githubusercontent.com/12017284/146837736-d87fcf14-caa5-4e32-94a5-ff7dd55f1c88.png)

**Comment by AndyTWF** [comment]
Thanks @hsugden - think we added the stands before any comprehensive detail appeared! This'll be fixed in the next API revision
