### ISSUE TITLE
Don't accept 1234 as pilot squawk

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-api#923]
I've had a lot of aircraft recently (mainly MSFS!) connect with the squawk code 1234 set, and then UKCP doesn't generate a new one for them - this would cause quite a few DUPEs if squawks aren't force regenerated. Could we ban this as a squawk altogether please? 😄

**Comment by hsugden** [comment]
Sorry @AndyTWF not sure whether I've got the right one here, api vs. plugin

**Comment by AndyTWF** [comment]
Bit of both @hsugden - I've patched the API to not assign 1234, but also the plugin itself to treat 1234 as unassigned :)
